### PR TITLE
Overloading position and words methods with a language parameter

### PR DESCRIPTION
**Pull request by tsamaya**

### CODE REVIEW

**Comment by tsamaya** [comment]
I also push the commit with Strings economy (#2 Avoid Strings concatenation. It consume too many objects and make Garbage Collector overwork)

**Comment by chrismayer** [comment]
Hi @tsamaya,

very good additions and improvements. Thanks a lot for this!
One question: Did you add your .gitignore file by purpose?

**Comment by tsamaya** [comment]
Hi @chrismayer 
Yes I think including a .gitignore file is usefull.

**Comment by chrismayer** [comment]
Hi @tsamaya,

thanks for your ongoing work.
I agree a .gitignore would be useful. Would you mind splitting up this PR in 2 or 3 separate PRs, so they are separated more thematically?  I think about something like:
- the initial one  "Overloading position and words methods with a language"
- one for adding the .gitignore
- one for adding the new test

So the review is much easier.

**Comment by tsamaya** [comment]
Hi @chrismayer 
I have done the first 2 PR. 
I am waiting the merged for the last PR with test class.

**Comment by chrismayer** [comment]
I merged #5 and #6 so I would suggest you can open another PR (if you want to) for the additional test and we close this PR afterwards, since it will be obsolete then.
Thanks for your ongoing effort, @tsamaya !

**Comment by tsamaya** [comment]
You are welcome !
I made the new PR #7
have a nice week end

**Comment by chrismayer** [comment]
Since #5, #6 and #7 are merged I will close this now. Thank you @tsamaya!

**Pull request closed without merging**
